const CHAT_CREATED = 'CHAT_CREATED';
const CHAT_UPDATED = 'CHAT_UPDATED';
const CHAT_DELETED = 'CHAT_DELETED';

const CHATROOM_CREATED = 'CHATROOM_CREATED';
const CHATROOM_UPDATED = 'CHATROOM_UPDATED';
const CHATROOM_DELETED = 'CHATROOM_DELETED';

module.exports = {
  CHAT_CREATED,
  CHAT_UPDATED,
  CHAT_DELETED,
  CHATROOM_CREATED,
  CHATROOM_UPDATED,
  CHATROOM_DELETED
};